### ISSUE TITLE
Index

### ISSUE THREAD

**Issue by crackhead** [Multivit4min/beguid-converter#2]
Wie hast du es mit der Indexierung gelöst haben 3 Milliarden Datensätze Convert PID -> GUID ohne Probleme jedoch umgekehrt 5% der anfragen gibts einen Error no Data.

Ich führe es auf die Indexierung zurück.

Gruß

**Comment by cat24max** [comment]
Hast du mal ein paar Beispiele für solche GUIDs?
https://beguid-converter.allianceapps.io ist mit 2 Mrd. generiert. Mehr wird man in absehbarer Zeit auch nicht brauchen.

**Comment by crackhead** [comment]
Perfekt hier zb. 7b2ace31da94c21474515e0d624a1a3ae
220389f41685a33e74861fab2324a40fb
Usw. Über Multi seiner api kein Thema

**Comment by cat24max** [comment]
Ich kann dir auch sagen, warum die nicht gehen, die oberen beiden sind keine gültigen MD5 Hashes. Sind jeweils 33 Zeichen lang, also 1 zu lang.
Ich Webserver wird /:guid([a-f0-9]{32}) abgefragt. Wenn das also keine 32-stellige Hexadezimalzahl ist, dann kommt "No matching route found".

**Comment by crackhead** [comment]
xD sind aktive Spieler die Grade aufm Server sind haha scheiß be trotzdem gibt es vereinzelt ids wie die letzte die nicht indexiert sind

**Comment by cat24max** [comment]
Über welchen RCON Client liest du das aus?

**Comment by crackhead** [comment]
https://github.com/felixms/arma-rcon-class-php

**Comment by crackhead** [comment]
select * from beguid where guid = UNHEX('1c696e');
/* Betroffene Zeilen: 0  Gefundene Zeilen: 0  Warnungen: 0  Dauer von 1 Abfrage: 0,000 sec. */

**Comment by cat24max** [comment]
Hm, da bekomme ich 115 Ergebnisse.
Kannst du zufällig grad TS kommen, ich hab nämlich einen bösen Verdacht woran die falschen GUIDs mit ARC.php liegen. Bin im Support Abgeschlossen Bereich.

**Comment by cat24max** [comment]
Schick mal bitte das gesamte Ergebnis von
`select * from beguid where guid = UNHEX('aaaaaa');`
rein.

**Comment by crackhead** [comment]
Schick mal bitte das gesamte Ergebnis von
select * from beguid where guid = UNHEX('aaaaaa');
rein.

Kein Ergebnis

**Comment by Multivit4min** [comment]
Wie groß ist denn deine Datenbank auf der Festplatte? Ich befürchte eher dass du anstatt 3 Milliarden nur 3 Millionen GUIDs generiert hast.

Wenn die Indexes nicht existieren dann würde die Query lediglich einige Minuten brauchen bis der Datenbank Server antwortet. Evt noch überprüfen ob du auf die richtige Datenbank zugreifst und die auch wirklich Daten drinnen hat

```sql
USE `DEINE_DATENBANK`;
SHOW TABLE STATUS FROM `DEINE_DATENBANK`;
```

**Comment by crackhead** [comment]
"beguid"	"MyISAM"	"10"	"Fixed"	"3000000000"	"9"	"27000000000"	"2533274790395903"	"36549961728"	"0"	\N	"2019-04-17 20:14:35"	"2019-04-20 07:58:24"	"2019-04-17 20:17:39"	"utf8mb4_unicode_ci"	\N	""	""

**Comment by Multivit4min** [comment]
Wie schauen die Daten in deiner Datenbank aus?
```sql
USE `DATABASE_NAME`;
SELECT * FROM `TABLE_NAME` LIMIT 100;
```

**Comment by crackhead** [comment]
`"0"	"0x0CC99E3A"
"1"	"0xCA5C318B"
"2"	"0x2FA56708"
"3"	"0x50B85DAA"
"4"	"0xB43236CC"
"5"	"0xCABAA34A"
"6"	"0x5432FAE6"
"7"	"0xE563955C"
"8"	"0x0576D688"
"9"	"0x7AEEDF40"
"10"	"0x9720BF41"
"11"	"0x1A720E1C"
"12"	"0x54C8D6EC"
"13"	"0x4500A574"
"14"	"0x8A95CE3A"
"15"	"0x53724F16"
"16"	"0x1C6F92A6"
"17"	"0x561C975A"
"18"	"0x8E9AA65B"
"19"	"0xDE9C46E0"
"20"	"0x0E611A9E"
"21"	"0x069BCB8C"
"22"	"0xB3D61047"
"23"	"0xBD68089A"
"24"	"0x74E89C9B"
"25"	"0x6656CDFC"
"26"	"0x93E4281A"
"27"	"0x61A4FC13"
"28"	"0x89BEE37D"
"29"	"0x0F4B988F"
"30"	"0x622616BC"
"31"	"0x83B6E9C0"
"32"	"0xD9F06082"
"33"	"0xF79984B7"
"34"	"0xD6B85844"
"35"	"0xBCEB1A8B"
"36"	"0xBDE6B169"
"37"	"0x5C144B22"
"38"	"0xB0CD5919"
"39"	"0x6C9FF1A9"
"40"	"0x91EBF38C"
"41"	"0xB9BAD7A3"
"42"	"0x5AC74F5E"
"43"	"0x723E5AF7"
"44"	"0xF2250E54"
"45"	"0x35055C6C"
"46"	"0x52BEE92D"
"47"	"0xBE2FDA2C"
"48"	"0xE1B6CA0C"
"49"	"0x0C30F175"
"50"	"0x71F21D3C"
"51"	"0xE508C1B8"
"52"	"0xFE2287D4"
"53"	"0xA46A6C30"
"54"	"0x8C0804AA"
"55"	"0x5C6F4FEE"
"56"	"0x82B61634"
"57"	"0xE4BB2617"
"58"	"0x617489CB"
"59"	"0x47AE5D06"
"60"	"0xA93D311C"
"61"	"0x002D19C1"
"62"	"0xCB0FE750"
"63"	"0x69701C80"
"64"	"0x5EE6245E"
"65"	"0x4CD66069"
"66"	"0x5BD15283"
"67"	"0xBB258111"
"68"	"0xCE616CC7"
"69"	"0x4F6104CD"
"70"	"0xB13D1EB2"
"71"	"0x9403C6D4"
"72"	"0xB87D74D2"
"73"	"0x3A6CC9E8"
"74"	"0x73F44B8E"
"75"	"0xE195B360"
"76"	"0x8DFCBE57"
"77"	"0x64E2F959"
"78"	"0xC7AD5594"
"79"	"0x7B998FEC"
"80"	"0xD901AF75"
"81"	"0xD0963104"
"82"	"0xC0C0B83E"
"83"	"0xDC6E25B1"
"84"	"0x5316D0DE"
"85"	"0x4292D56F"
"86"	"0x2BAC10D3"
"87"	"0x5C72F8ED"
"88"	"0xED12F2C5"
"89"	"0x18728FE3"
"90"	"0x1AC0A3C1"
"91"	"0xB0F0743D"
"92"	"0x98F391D2"
"93"	"0x59EABEB1"
"94"	"0x64F93D6B"
"95"	"0xE92D7A9E"
"96"	"0x45544D5C"
"97"	"0x8BA19512"
"98"	"0xE988215E"
"99"	"0x423E1618"
`

**Comment by Multivit4min** [comment]
kannst du mir noch deine config.js posten?

**Comment by cat24max** [comment]
Das schaut mir nach 8 Hex-Zahlen pro GUID aus statt 6

**Comment by crackhead** [comment]
module.exports = {
  //Webserver Listenport
  listenport: 8888,

  //set additional headers for the http response
  headers: {
     "Access-Control-Allow-Origin": "*"
  },

  //Data directory for caching
  datadir: `${__dirname}/data`,

  //Cache
  cache: {
    //Time to keep Data in Cache
    keep_time: 14 * 24 * 60 * 60 * 1000,  //14 days
    //Cache Save to Disk Interval
    save_interval: 1 * 60 * 60 * 1000     //1 hour
  },

  //maximum allowed keys in post request
  post_key_limit:  250,

  //Database
  mysql: {
    //Connection Schema doc: https://github.com/mysqljs/mysql#connection-options
    conn: {
      host:       "***.***.***.***",  //mysql hostname
      port:       3306,         //mysql database port
      user:       "guid",           //mysql username
      password:   "*********",           //mysql password
      database:   "guid",           //mysql database name
      connectionLimit: 5        //mysql connection pool
    },
    //mysql table name
    table: "beguid"
  },

  generator: {
    //how much inserts should be done per batch
    batchsize: 50000n //(LEAVE the n at the end of the number!!!!)
  },

  //engine related stuff
  //do not touch if you do not know what you do :P
  guid: {
    //this defines how much chars of the guid will get saved
    //should be a multiple of 2
    //defines how much characters of the guid should be saved in the database
    //it is recommended to use either 6 or 8
    //length of 6: needs 17.6GB Disk Space per billion ids -> uses more CPU per request (but barely noticeable)
    //length of 8: needs 19.6GB Disk Space per billion ids -> requires less CPU per request
    length: 8,
  },

  steamid: {
    //the first valid existing steamid, should probably never be changed
    offset: 76561197960265730n, //(LEAVE the n at the end of the number!!!!)
  },

}

**Comment by Multivit4min** [comment]
Hmm das ist komisch, warum deine BE GUIDs eine länge von 33 haben finde ich selber merkwürdig,
MD5 sollte definitiv eine länge von 32 chars haben, 2 IDs von dir haben jedoch eine länge von 33

Zu dem thema mit der `632a2939c0e3376dd59e4842c05db21d` hast du mir da die Steam ID dazu?
Es gibt tatsächlich einige wenige SteamIDs die utopisch hoch sind und ich selber nicht sicher bin wie Steam auf derartige IDs kommt da die komplett aus dem Zusammenhang nicht inkremental erhöht werden wie die meisten anderen.

Unter anderem hat der Headless Client meist eine GUID welche nicht auf eine SteamID aufgelöst werden kann

Die Queries von @cat24max haben nicht funktioniert da er nicht wusste dass du eine länge von 8 generierst
```sql
select * from beguid where guid = UNHEX('aaaaaaaa');
```
hiermit müsste er eventuell ein wenig was finden jedoch die oberen BEGUIDs mit der länge von 33 sind ziemlich sicher nicht valide

von der SteamID zu GUID berrechnet die API das selber da das schneller geht als in der Datenbank nachzuschauen, da kannst du praktisch alles angeben und es wird zu einer möglichen GUID umgerechnet

**Comment by crackhead** [comment]
select * from beguid where guid = UNHEX('aaaaaaaa');

ausgabe:
"633599291"	"0xAAAAAAAA"

**Comment by cat24max** [comment]
Ja gut, ich kann jetzt nicht mehr weiterhelfen - meine DB hat nur 6 Zeichen und damit sind die Ergebnisse halt komplett anders.

**Comment by crackhead** [comment]
Tatsächlich ich habe jetzt alle ids verglichen sind 33 Stellig die nicht auflösbar sind lul
